import { AlertTriangle, CheckCircle2, Eye, Gauge, Lightbulb, TrainFront } from "lucide-react";

function Car({ x, y, color = "#fbbf24", rotate = 0 }: { x: number; y: number; color?: string; rotate?: number }) {
  return <g transform={`translate(${x} ${y}) rotate(${rotate})`}><rect x="-22" y="-11" width="44" height="22" rx="5" fill={color} /><rect x="-9" y="-8" width="18" height="16" rx="3" fill="#dbeafe" /><circle cx="-13" cy="12" r="4" fill="#0b1024" /><circle cx="13" cy="12" r="4" fill="#0b1024" /></g>;
}

function Arrow({ d, color = "#fbbf24" }: { d: string; color?: string }) {
  return <path d={d} fill="none" stroke={color} strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" />;
}

function EqualIntersection() {
  return <svg viewBox="0 0 420 260" role="img" aria-label="Egyenrangú kereszteződés: a jobbról érkező jármű halad elsőként" className="w-full rounded-2xl border border-white/10 bg-[#0d162d]">
    <rect width="420" height="260" fill="#11203d" /><path d="M0 95h420M0 165h420M160 0v260M260 0v260" stroke="#64748b" strokeWidth="70" /><path d="M0 95h420M0 165h420M160 0v260M260 0v260" stroke="#f8fafc" strokeOpacity=".4" strokeWidth="2" /><path d="M210 0v260M0 130h420" stroke="#f8fafc" strokeOpacity=".8" strokeWidth="2" strokeDasharray="10 10" />
    <Car x={110} y={130} /><Car x={210} y={210} color="#e2e8f0" rotate={-90} /><Arrow d="M135 130h75m-18-12 18 12-18 12" /><Arrow d="M210 186v-46m-12 18 12-18 12 18" color="#e2e8f0" />
    <circle cx="210" cy="130" r="34" fill="#0a1124" stroke="#fbbf24" strokeWidth="2" /><text x="210" y="125" fill="#fbbf24" textAnchor="middle" fontSize="13" fontWeight="700">JOBBRÓL</text><text x="210" y="143" fill="#f8fafc" textAnchor="middle" fontSize="11">elsőbbség</text>
  </svg>;
}

function LeftTurn() {
  return <svg viewBox="0 0 420 260" role="img" aria-label="Balra kanyarodó jármű elsőbbséget ad a szemből egyenesen érkezőnek" className="w-full rounded-2xl border border-white/10 bg-[#0d162d]">
    <rect width="420" height="260" fill="#11203d" /><path d="M0 65h420M0 195h420" stroke="#64748b" strokeWidth="130" /><path d="M0 65h420M0 195h420" stroke="#f8fafc" strokeOpacity=".4" strokeWidth="2" /><path d="M0 130h420" stroke="#f8fafc" strokeOpacity=".85" strokeWidth="2" strokeDasharray="12 10" />
    <Car x={105} y={98} /><Car x={315} y={162} color="#e2e8f0" rotate={180} /><Arrow d="M128 98h85m-20-12 20 12-20 12" /><Arrow d="M292 162h-85m20-12-20 12 20 12" color="#e2e8f0" /><path d="M216 98c32 0 36 22 36 43v27" fill="none" stroke="#fbbf24" strokeWidth="4" strokeLinecap="round" /><path d="M240 155l12 13 12-13" fill="none" stroke="#fbbf24" strokeWidth="4" />
    <rect x="128" y="207" width="165" height="28" rx="14" fill="#0a1124" stroke="#fbbf24" /><text x="210" y="226" fill="#f8fafc" textAnchor="middle" fontSize="12">A balra kanyarodó vár.</text>
  </svg>;
}

function Zebra() {
  return <svg viewBox="0 0 420 260" role="img" aria-label="Zebra előtt a gyalogosnak elsőbbséget kell adni" className="w-full rounded-2xl border border-white/10 bg-[#0d162d]">
    <rect width="420" height="260" fill="#11203d" /><rect y="55" width="420" height="150" fill="#64748b" /><path d="M0 130h420" stroke="#f8fafc" strokeOpacity=".8" strokeWidth="2" strokeDasharray="12 10" />
    {[145, 163, 181, 199, 217, 235, 253].map((x) => <rect key={x} x={x} y="57" width="11" height="146" fill="#f8fafc" fillOpacity=".9" />)}<Car x={78} y={95} /><Arrow d="M103 95h34m-13-10 13 10-13 10" /><circle cx="260" cy="105" r="9" fill="#f8fafc" /><path d="M260 114v31m0-22-13 13m13-13 13 13m-13 9-11 21m11-21 12 21" stroke="#f8fafc" strokeWidth="5" strokeLinecap="round" /><rect x="31" y="216" width="358" height="26" rx="13" fill="#0a1124" stroke="#fbbf24" /><text x="210" y="234" fill="#f8fafc" textAnchor="middle" fontSize="12">Lassíts, figyelj és adj elsőbbséget.</text>
  </svg>;
}

const checklist = ["Tükör: mi történik mögötted és melletted?", "Irányjelző: időben jelezz a szándékodról.", "Holttér: fordítsd el a fejed, ne csak a tükröt nézd.", "Sebesség: lassíts annyira, hogy legyen döntési időd.", "Manőver: csak akkor kezdd el, ha senkit sem akadályozol."];

export default function KreszGuide() {
  return <article className="mx-auto max-w-6xl px-6">
    <header className="rounded-3xl border border-amber-400/30 bg-gradient-to-br from-amber-400/15 via-[#1d2a49] to-[#15203a] p-7 md:p-10">
      <p className="text-xs font-black uppercase tracking-[0.25em] text-amber-300">Prémium Autósiskola · vezetési mankó</p>
      <h1 className="mt-4 max-w-4xl text-4xl font-black md:text-6xl">KRESZ a valódi forgalomban</h1>
      <p className="mt-5 max-w-3xl text-lg leading-8 text-slate-200">Nem paragrafusgyűjtemény: helyzetek, döntési sorrendek és vizuális ábrák azokhoz a pillanatokhoz, amikor egyedül ülsz először az autóban.</p>
      <nav aria-label="Témakörök" className="mt-8 flex flex-wrap gap-2">{["Elsőbbség", "Manőver", "Sebesség", "Gyalogos", "Vasúti átjáró"].map((item) => <a key={item} href={`#${item.toLocaleLowerCase().replace(" ", "-")}`} className="rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-bold text-white transition hover:border-amber-400 hover:text-amber-300">{item}</a>)}</nav>
    </header>

    <section className="mt-10 grid gap-5 md:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-[#1d2a49] p-5"><Eye className="h-7 w-7 text-amber-400" /><h2 className="mt-4 text-lg font-black">Láss előre</h2><p className="mt-2 text-sm leading-6 text-slate-300">Ne csak az előtted lévő autót nézd: figyeld a kereszteződést, zebrákat, tükröket és a lehetséges menekülő utat.</p></div><div className="rounded-2xl border border-white/10 bg-[#1d2a49] p-5"><Gauge className="h-7 w-7 text-amber-400" /><h2 className="mt-4 text-lg font-black">Lassíts időben</h2><p className="mt-2 text-sm leading-6 text-slate-300">A jó döntéshez idő kell. Kétséges helyzetben a kisebb sebesség mindig több információt ad.</p></div><div className="rounded-2xl border border-white/10 bg-[#1d2a49] p-5"><Lightbulb className="h-7 w-7 text-amber-400" /><h2 className="mt-4 text-lg font-black">Legyél egyértelmű</h2><p className="mt-2 text-sm leading-6 text-slate-300">Időben jelezz, tarts kiszámítható ívet és ne vedd el mások döntési idejét hirtelen manőverrel.</p></div></section>

    <section id="elsőbbség" className="mt-16"><p className="text-sm font-black uppercase tracking-[0.22em] text-amber-400">01 · Elsőbbség</p><h2 className="mt-3 text-3xl font-black md:text-4xl">Három helyzet, amit érdemes automatikusan felismerni</h2><p className="mt-4 max-w-3xl leading-7 text-slate-300">Az irányító rendőr utasítása megelőzi a fényjelzést, a fényjelzés a jelzőtáblát, a jelzőtábla pedig az általános szabályt. Ha nincs külön jelzés, lassíts és olvasd a helyzetet.</p>
      <div className="mt-8 grid gap-6 lg:grid-cols-3"><Scenario title="Egyenrangú utak" tag="Jobbkézszabály" diagram={<EqualIntersection />} text="Ha nincs jelzőtábla vagy lámpa, az egyenrangú utak találkozásánál a jobbról érkezőnek adj elsőbbséget. Ne abból indulj ki, hogy a másik biztosan megáll." /><Scenario title="Balra kanyarodás" tag="Szemből érkező" diagram={<LeftTurn />} text="Irányváltoztatáskor az egyenesen haladót ne kényszerítsd fékezésre. Türelmesen várd meg, amíg a szemből érkező forgalom elhalad." /><Scenario title="Gyalogátkelőhely" tag="Zebra" diagram={<Zebra />} text="Zebra közelében vedd vissza a sebességet. A takarásból kilépő gyalogosra, gyermekre és az út szélén várakozóra is számíts." /></div>
    </section>

    <section id="manőver" className="mt-16 rounded-3xl border border-white/10 bg-[#1b2948] p-7 md:p-10"><p className="text-sm font-black uppercase tracking-[0.22em] text-amber-400">02 · Manőver</p><h2 className="mt-3 text-3xl font-black">Az 5 lépéses „ne kapkodj” rutin</h2><p className="mt-4 max-w-3xl leading-7 text-slate-300">Használd indulásnál, sávváltásnál, előzésnél, bekanyarodásnál és megállásnál. A sorrend segít, hogy ne maradjon ki a holttér ellenőrzése.</p><ol className="mt-7 grid gap-3 md:grid-cols-5">{checklist.map((item, index) => <li key={item} className="rounded-2xl border border-white/10 bg-[#233457] p-4"><span className="text-xs font-black text-amber-400">0{index + 1}</span><p className="mt-2 text-sm font-semibold leading-6 text-white">{item}</p></li>)}</ol></section>

    <section id="sebesség" className="mt-16"><p className="text-sm font-black uppercase tracking-[0.22em] text-amber-400">03 · Sebesség</p><h2 className="mt-3 text-3xl font-black">A táblán lévő szám felső határ</h2><p className="mt-4 max-w-3xl leading-7 text-slate-300">Személyautóval, külön korlátozó jelzés hiányában az alábbi maximumok érvényesek. A látási, út- és forgalmi viszonyok miatt ennél lassabban kell menni, ha a biztonság ezt kívánja.</p><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Lakott terület", "50"], ["Lakott területen kívül", "90"], ["Autóút", "110"], ["Autópálya", "130"]].map(([label, speed]) => <div key={label} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-[#1d2a49] p-5"><span className="flex h-16 w-16 items-center justify-center rounded-full border-4 border-red-500 bg-white text-xl font-black text-slate-900">{speed}</span><div><p className="font-bold">{label}</p><p className="text-sm text-slate-400">km/óra maximum</p></div></div>)}</div></section>

    <section id="gyalogos" className="mt-16 grid gap-7 lg:grid-cols-2"><div className="rounded-3xl border border-amber-400/25 bg-[#1d2a49] p-7"><p className="text-sm font-black uppercase tracking-[0.22em] text-amber-400">04 · Sérülékeny közlekedők</p><h2 className="mt-3 text-3xl font-black">Amit a kezdők gyakran későn vesznek észre</h2><ul className="mt-6 space-y-4 text-slate-200"><li className="flex gap-3"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-amber-400" />Parkoló autó ajtaja vagy jármű mögül kilépő gyalogos.</li><li className="flex gap-3"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-amber-400" />Kerékpáros a holttérben vagy az út szélén.</li><li className="flex gap-3"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-amber-400" />Gyermek, idős ember vagy babakocsi zebra környékén.</li><li className="flex gap-3"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-amber-400" />Ajtónyitás előtt mindig nézz hátra is.</li></ul></div><div className="rounded-3xl border border-white/10 bg-[#1b2948] p-7"><p className="text-sm font-black uppercase tracking-[0.22em] text-amber-400">05 · Kockázatkezelés</p><h2 className="mt-3 text-3xl font-black">Eső, sötét, idegen útvonal</h2><p className="mt-5 leading-7 text-slate-300">Ilyenkor hosszabb fékút, rosszabb látás és több bizonytalanság várható. Növeld a követési távolságot, lassíts hamarabb és ne siess át a sárgán csak azért, mert „még beleférne”.</p><div className="mt-6 rounded-2xl border border-amber-400/25 bg-amber-400/10 p-4 text-sm leading-6 text-amber-100"><AlertTriangle className="mb-2 h-5 w-5 text-amber-300" />Ha nem látod át a helyzetet, az nem azt jelenti, hogy nincs veszély — azt jelenti, hogy lassítani kell.</div></div></section>

    <section id="vasúti-átjáró" className="mt-16 rounded-3xl border border-red-400/35 bg-gradient-to-br from-red-950/45 to-[#1d2a49] p-7 md:p-10"><div className="flex gap-4"><TrainFront className="h-10 w-10 shrink-0 text-red-300" /><div><p className="text-sm font-black uppercase tracking-[0.22em] text-red-200">06 · Vasúti átjáró</p><h2 className="mt-2 text-3xl font-black">Itt nincs „még átérek”</h2></div></div><div className="mt-7 grid gap-6 md:grid-cols-2"><div><p className="font-bold text-white">Minden alkalommal ezt ellenőrizd:</p><ul className="mt-4 space-y-3 text-slate-200"><li>• Van-e közeledő vonat, hangjelzés vagy piros villogás?</li><li>• Teljesen nyitva van-e a sorompó?</li><li>Villog-e a fehér fény, ha van fénysorompó?</li><li>Át tudsz-e haladni megállás nélkül?</li></ul></div><div className="rounded-2xl border border-red-300/30 bg-red-950/30 p-5 text-sm leading-7 text-red-100"><strong>Állj meg, ha bizonytalan vagy.</strong><br />Az átjáróra csak akkor hajts rá, ha biztosan folyamatosan át tudsz haladni. Biztosítatlan átjárónál nézz el mindkét irányba, és győződj meg róla, hogy nem közeledik vonat.</div></div></section>

    <aside className="mt-12 rounded-2xl border border-amber-400/30 bg-amber-400/10 p-5 text-sm leading-7 text-amber-100"><strong>Fontos:</strong> ez a segédlet az alapelvek megértését támogatja. Egy konkrét forgalmi helyzetben a helyszíni jelzések, a forgalomirányítás és a hatályos jogszabály teljes szövege az irányadó. A részletes hivatalos KRESZ: <a className="font-bold underline underline-offset-4" href="https://njt.hu/jogszabaly/1975-1-20-24.33" target="_blank" rel="noreferrer">Nemzeti Jogszabálytár</a>.</aside>
  </article>;
}

function Scenario({ title, tag, text, diagram }: { title: string; tag: string; text: string; diagram: React.ReactNode }) {
  return <article className="overflow-hidden rounded-3xl border border-white/10 bg-[#1d2a49]"><div className="p-4">{diagram}</div><div className="border-t border-white/10 p-6"><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-400">{tag}</p><h3 className="mt-2 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-300">{text}</p></div></article>;
}
