"use client";

import { useState, useTransition, type ReactNode } from "react";
import { CheckCircle2, CircleCheck, FileCheck2, LockKeyhole } from "lucide-react";
import Link from "next/link";
import { submitApplication } from "./actions";

type Course = { id: string; title: string };
const inputClass = "mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-amber-400 focus:ring-2 focus:ring-amber-400/20";
const labelClass = "text-sm font-semibold text-slate-200";

export default function ApplicationForm({ courses, initialCourseId }: { courses: Course[]; initialCourseId?: string }) {
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState("");
  const [isMinor, setIsMinor] = useState(false);
  const [hasLicence, setHasLicence] = useState(false);
  const [selectedCourse, setSelectedCourse] = useState(courses.some((course) => course.id === initialCourseId) ? initialCourseId! : courses[0]?.id ?? "");
  const submit = (formData: FormData) => startTransition(async () => { try { const result = await submitApplication(formData); if (result.ok) { setMessage("Sikeres jelentkezés! Hamarosan felvesszük veled a kapcsolatot."); } } catch (error) { setMessage(error instanceof Error ? error.message : "Sikertelen mentés."); } });

  if (courses.length === 0) return <p className="rounded-2xl border border-amber-400/30 bg-white/5 p-8 text-center text-slate-300">Jelenleg nincs elérhető képzés.</p>;
  return <form action={submit} className="space-y-8">
    <section className="rounded-3xl border border-amber-400/30 bg-gradient-to-br from-amber-400/15 to-white/5 p-6 shadow-xl shadow-black/20 md:p-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-300">1. Képzés kiválasztása</p><div className="mt-5"><label className={labelClass}>Választott kategória<select name="course_id" value={selectedCourse} onChange={(event) => setSelectedCourse(event.target.value)} className={inputClass}>{courses.map((course) => <option key={course.id} value={course.id}>{course.title}</option>)}</select></label></div></section>

    <section className="rounded-3xl border border-amber-400/30 bg-amber-400/5 p-6 md:p-8"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-amber-400 text-[#050816]"><FileCheck2 className="h-5 w-5" /></div><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-300">Beiratkozás előtt</p><h2 className="mt-1 text-xl font-black text-white">Ezeket készítsd elő</h2></div></div><div className="mt-6 grid gap-6 md:grid-cols-2"><div><p className="font-bold text-white">Szükséges dokumentumok</p><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-200"><Requirement>Érvényes személyazonosító igazolvány vagy útlevél</Requirement><Requirement>Érvényes lakcímkártya</Requirement><Requirement>Az alapfokú végzettséget igazoló bizonyítvány (legalább 8 általános)</Requirement><Requirement>Meglévő jogosítvány, ha már rendelkezel más kategóriával</Requirement><Requirement>Orvosi alkalmassági igazolás, ha a választott képzéshez szükséges</Requirement></ul></div><div className="rounded-2xl border border-white/10 bg-black/20 p-5"><p className="font-bold text-white">A kiválasztott képzés feltételei</p><p className="mt-3 text-sm leading-6 text-slate-300">A pontos életkori és alkalmassági feltételeket a képzés kiválasztása után ellenőrizzük. B kategóriánál a tanfolyam 16,5 éves kortól kezdhető, és EÜ 1. csoportú orvosi alkalmasság szükséges.</p><p className="mt-3 text-xs leading-5 text-slate-400">Bizonytalan vagy? Küldd el a jelentkezést, és még a beiratkozás előtt egyeztetünk veled.</p></div></div></section>

    <fieldset className="rounded-3xl border border-white/10 bg-white/5 p-6 md:p-8"><legend className="px-2 text-lg font-black text-amber-400">2. Tanuló viselt neve</legend><div className="mt-4 grid gap-4 md:grid-cols-3"><Input name="last_name" label="Vezetéknév" required /><Input name="first_name" label="Keresztnév" required /><Input name="middle_name" label="Utónév (ha van)" /></div><p className="mt-7 text-sm font-bold text-slate-200">Születési név (ha eltér a viselt névtől)</p><div className="mt-3 grid gap-4 md:grid-cols-3"><Input name="birth_last_name" label="Vezetéknév" /><Input name="birth_first_name" label="Keresztnév" /><Input name="birth_middle_name" label="Utónév" /></div></fieldset>

    <fieldset className="rounded-3xl border border-white/10 bg-white/5 p-6 md:p-8"><legend className="px-2 text-lg font-black text-amber-400">3. Születési és családi adatok</legend><div className="mt-4 grid gap-4 md:grid-cols-3"><Input name="birth_place" label="Születési hely" required /><Input name="birth_date" label="Születési idő" type="date" required /><Input name="citizenship" label="Állampolgárság" required /></div><p className="mt-7 text-sm font-bold text-slate-200">Anyja leánykori neve</p><div className="mt-3 grid gap-4 md:grid-cols-3"><Input name="mother_last_name" label="Vezetéknév" required /><Input name="mother_first_name" label="Keresztnév" required /><Input name="mother_middle_name" label="Utónév (ha van)" /></div></fieldset>

    <fieldset className="rounded-3xl border border-white/10 bg-white/5 p-6 md:p-8"><legend className="px-2 text-lg font-black text-amber-400">4. Kapcsolattartás és azonosítás</legend><div className="mt-4 grid gap-4 md:grid-cols-2"><Input name="phone" label="Telefonszám" type="tel" required /><Input name="email" label="E-mail cím" type="email" required /><Input name="postal_code" label="Irányítószám" required /><Input name="city" label="Település" required /><Input name="street_address" label="Utca, házszám" required /><Input name="mailing_address" label="Levelezési cím (ha eltér)" /><Input name="identity_number" label="Személyi igazolvány száma" required /><Input name="identity_expiry" label="Személyi igazolvány érvényessége" type="date" required /><Input name="tax_id" label="Adóazonosító jel" required /></div><label className={`mt-4 block ${labelClass}`}>Iskolai végzettség<select name="education" required className={inputClass}><option value="">Válassz</option><option>Általános iskolai végzettség</option><option>Középfokú végzettség</option><option>Felsőfokú végzettség</option></select></label></fieldset>

    <fieldset className="rounded-3xl border border-white/10 bg-white/5 p-6 md:p-8"><legend className="px-2 text-lg font-black text-amber-400">5. Képzési információk</legend><div className="mt-4 grid gap-6 md:grid-cols-2"><RadioGroup name="applicant_type" label="Kezdő vagy átjelentkező?" options={[['beginner','Kezdő'],['transfer','Átjelentkező']]} /><RadioGroup name="medical_fitness" label="EÜ alkalmasság" options={[['none','Nincs'],['has','Van']]} /><RadioGroup name="applicant_age" label="A jelentkező" options={[['adult','Nagykorú'],['minor','Kiskorú']]} onChange={(value) => setIsMinor(value === 'minor')} /><RadioGroup name="licence_status" label="Van más kategóriájú jogosítvány?" options={[['none','Nincs'],['has','Van']]} onChange={(value) => setHasLicence(value === 'has')} /></div><div className="mt-6 rounded-2xl border border-white/10 bg-black/20 p-5"><label className={labelClass}>Orvosi alkalmassági igazolás <span className="font-normal text-slate-400">(opcionális)</span><input name="medical_document" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="mt-2 block w-full cursor-pointer rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 file:mr-4 file:rounded-lg file:border-0 file:bg-amber-400 file:px-3 file:py-2 file:font-bold file:text-black hover:file:bg-amber-300" /></label><p className="mt-2 text-xs leading-5 text-slate-400">PDF, JPG, PNG vagy WEBP; legfeljebb 8 MB. A fájlt kizárólag a jelentkezés feldolgozására jogosult adminisztrátorok érhetik el.</p></div>{isMinor && <div className="mt-6 rounded-2xl border border-amber-400/25 bg-amber-400/5 p-5"><p className="font-bold text-amber-300">Gondviselő adatai</p><div className="mt-4 grid gap-4 md:grid-cols-3"><Input name="guardian_name" label="Gondviselő neve" required /><Input name="guardian_phone" label="Gondviselő telefonszáma" type="tel" required /><Input name="guardian_email" label="Gondviselő e-mail címe" type="email" required /></div></div>}{hasLicence && <div className="mt-6"><Input name="licence_number" label="Jogosítvány száma" required /></div>}<div className="mt-7"><p className={labelClass}>Legkedvezőbb vezetési idők</p><div className="mt-3 grid gap-3 md:grid-cols-3"><Check name="preferred_driving_times" value="Munkanapokon délelőtt" label="Munkanapokon délelőtt" /><Check name="preferred_driving_times" value="Munkanapokon délután" label="Munkanapokon délután" /><Check name="preferred_driving_times" value="Hétvégén" label="Hétvégén" /></div></div></fieldset>

    <input tabIndex={-1} autoComplete="off" name="honeypot" className="hidden" aria-hidden />
    <section className="rounded-3xl border border-amber-400/30 bg-black/25 p-6 md:p-8"><label className="flex items-start gap-3 text-sm leading-6 text-slate-200"><input name="privacy_consent" required type="checkbox" className="mt-1 h-4 w-4 accent-amber-400" /><span>Elolvastam és elfogadom az <Link className="font-bold text-amber-300 underline underline-offset-4" href="/adatkezeles" target="_blank">adatkezelési tájékoztatót</Link>, és hozzájárulok személyes adataim, valamint feltöltés esetén az orvosi alkalmassági igazolásomban szereplő egészségügyi adatok jelentkezés céljából történő kezeléséhez.</span></label><p className="mt-4 flex items-center gap-2 text-xs text-slate-400"><LockKeyhole className="h-4 w-4 text-amber-400" />Az adatokat kizárólag a jelentkezés feldolgozására jogosult munkatársak látják.</p><button disabled={pending} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-amber-300 to-amber-500 px-7 py-4 font-black text-black disabled:opacity-60"><CheckCircle2 className="h-5 w-5" />{pending ? "Küldés folyamatban…" : "Jelentkezés elküldése"}</button>{message && <p aria-live="polite" className="mt-4 font-semibold text-amber-200">{message}</p>}</section>
  </form>;
}

function Input({ label, name, required, type = "text" }: { label: string; name: string; required?: boolean; type?: string }) { return <label className={labelClass}>{label}{required && <span className="ml-1 text-amber-400">*</span>}<input name={name} required={required} type={type} className={inputClass} /></label>; }
function Check({ name, value, label }: { name: string; value: string; label: string }) { return <label className="flex items-center gap-3 rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-slate-200"><input name={name} value={value} type="checkbox" className="h-4 w-4 accent-amber-400" />{label}</label>; }
function Requirement({ children }: { children: ReactNode }) { return <li className="flex gap-2"><CircleCheck className="mt-1 h-4 w-4 shrink-0 text-amber-400" />{children}</li>; }
function RadioGroup({ name, label, options, onChange }: { name: string; label: string; options: [string, string][]; onChange?: (value: string) => void }) { return <div><p className={labelClass}>{label}</p><div className="mt-3 flex flex-wrap gap-3">{options.map(([value, text]) => <label key={value} className="flex items-center gap-2 rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm"><input name={name} value={value} type="radio" required onChange={() => onChange?.(value)} className="accent-amber-400" />{text}</label>)}</div></div>; }
