import Link from "next/link";
import Footer from "@/app/components/Footer";
import Header from "@/app/components/Header";

export const metadata = { title: "Általános Szerződési Feltételek" };

const sections = [
  ["1. Szolgáltató és hatály", "A szolgáltató a Prémium Oktatás Korlátolt Felelősségű Társaság (Prémium Oktatás Kft.; Cg. 15-09-086978; adószám: 27289936-1-15; székhely: 4400 Nyíregyháza, Toldi utca 69. 1. em. 11. ajtó), kereskedelmi nevén Prémium Autósiskola. Az ügyfélfogadó iroda címe: 4400 Nyíregyháza, Széchenyi utca 17. földszint 2U. ajtó. Elérhetőség: info@premiumautosiskola.hu, +36-30-235-2597. A jelen feltételek az autósiskola által meghirdetett AM, A1, A2, A és B kategóriás képzésekre vonatkoznak."],
  ["2. Jelentkezés és szerződéskötés", "Jelentkezni az ügyfélfogadó irodában, illetve előzetes online jelentkezéssel lehet. Az online űrlap elküldése még nem hoz létre képzési szerződést. A szerződés akkor jön létre, amikor az autósiskola a jelentkező feltételeit ellenőrizte, és a felek írásbeli, személyre szóló képzési szerződést kötnek. Kiskorú tanuló esetén a törvényes képviselő közreműködése és aláírása is szükséges."],
  ["3. A képzés feltételei", "A tanulónak meg kell felelnie a választott kategória jogszabályi életkori, egészségi, iskolai végzettségi és közlekedésbiztonsági feltételeinek. A felvételhez szükséges okmányokat és igazolásokat az autósiskola ellenőrizheti. Az elméleti képzés e-learning formában is történhet; az alaphozzáférés 75 óra, a képzés kezdetétől számított 180 nap. A részletes kategóriafeltételeket az írásbeli tájékoztató tartalmazza."],
  ["4. Díjak és fizetés", "A képzési és vizsgadíjakat az aktuális árlista, az írásbeli tájékoztató és a tanulóval kötött szerződés tartalmazza. A tanfolyam megkezdésének feltétele a szerződésben megjelölt első részlet és a szükséges vizsgadíjak megfizetése. A tandíj az irodában, számla ellenében vagy átutalással fizethető a 10410400-00000190-33608936 bankszámlára, kedvezményezett: Prémium Autósiskola. Az oktatónak készpénzt átadni nem szabad."],
  ["5. Oktatás, késés és lemondás", "A gyakorlati időpontokat a tanuló és az oktató előre egyezteti. Ha a tanóra a tanuló hibájából marad el, illetve a tanuló a rendtartás szerinti lemondási jogával nem él, a tervezett órák felének díját köteles megfizetni. Az oktató a tanuló megjelenésére az első 20 percben köteles várni. Ha a tanóra nem a tanuló hibájából marad el, az autósiskola másik időpontban biztosítja azt."],
  ["6. Vizsgák", "A vizsgára bocsátás feltétele a vonatkozó tantervi követelmények, az előírt óraszám és menettávolság, valamint a díjfizetési feltételek teljesítése. A tanulónak a vizsga helyszínén pontosan kell megjelennie és személyazonosságát igazolnia kell. A vizsgák részletes rendjét a vizsgaszervezet szabályai és az írásbeli tájékoztató ismerteti."],
  ["7. A képzés megszakítása és áthelyezés", "A tanuló írásbeli kérésére az autósiskola a képzést megszakítja, az addig elvégzett képzésről pedig hivatalos igazolást ad ki. A befizetett, de szolgáltatással nem teljesített díjrész visszajár; az autósiskola ezért kezelési költséget nem számít fel. Más képzőszervhez történő áthelyezésnél a tanuló a kedvezményeit elveszítheti, és a szerződésben rögzített különbözet fizetendő lehet."],
  ["8. Magatartási és biztonsági szabályok", "A tanuló köteles a baleset-, tűzvédelmi és oktatási szabályokat betartani. Alkohol vagy más bódító szer hatása alatt az oktatáson és vizsgán részt venni tilos. Súlyos rendzavarás vagy veszélyeztető magatartás esetén az autósiskola azonnali hatállyal megszüntetheti a szerződést; ilyen esetben a tandíj nem jár vissza."],
  ["9. Panaszkezelés", "Panaszt és észrevételt először az oktatónál, eredménytelenség esetén az ügyfélfogadó irodában vagy Kicska Gábor Zoltán iskolavezetőnél lehet jelezni. Az iskolavezető e-mail-címe: kicska82@gmail.com, telefonszáma: +36-30-235-2597. Fogadóórája szerdán 15:00–16:00 között, illetve előzetes telefonos egyeztetéssel van."],
  ["10. Adatkezelés és záró rendelkezések", "A személyes adatok kezeléséről az Adatkezelési tájékoztató rendelkezik. A jelen feltételekben nem szabályozott kérdésekben a Polgári Törvénykönyv, a járművezető-képzésre vonatkozó jogszabályok és a tanulóval kötött képzési szerződés az irányadó. A feltételek hatályos változata a weboldalon és az ügyfélfogadó irodában érhető el."],
];

export default function TermsPage() { return <><Header /><main className="min-h-screen bg-[#15203a] pb-24 pt-32 text-slate-200"><article className="mx-auto max-w-4xl px-6"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-amber-400">Prémium Autósiskola</p><h1 className="mt-4 text-4xl font-black text-white md:text-5xl">Általános Szerződési Feltételek</h1><p className="mt-4 text-sm text-slate-400">Hatályos: 2026. szeptember 25.</p><div className="mt-10 space-y-6">{sections.map(([title, text]) => <section key={title} className="rounded-3xl border border-white/10 bg-white/5 p-6 leading-7 md:p-8"><h2 className="text-2xl font-black text-white">{title}</h2><p className="mt-4">{text}</p></section>)}</div><p className="mt-8 text-sm text-slate-400">Az online jelentkezés során kezelt adatok részleteit az <Link className="text-amber-300 underline underline-offset-4" href="/adatkezeles">Adatkezelési tájékoztató</Link> tartalmazza.</p></article></main><Footer settings={null} /></>; }
