import Link from "next/link";
import Footer from "@/app/components/Footer";
import Header from "@/app/components/Header";

export const metadata = { title: "Általános Szerződési Feltételek" };

const sections = [
  ["1. Szolgáltató és hatály", "A szolgáltató a Prémium Oktatás Korlátolt Felelősségű Társaság (Prémium Oktatás Kft.; Cg. 15-09-086978; adószám: 27289936-1-15; székhely: 4400 Nyíregyháza, Toldi utca 69. 1. em. 11. ajtó), kereskedelmi nevén Prémium Autósiskola. Az ügyfélfogadó iroda címe: 4400 Nyíregyháza, Széchenyi utca 17. földszint 2U. ajtó. Elérhetőség: info@premiumautosiskola.hu, +36-30-235-2597. A jelen feltételek az autósiskola által meghirdetett AM, A1, A2, A és B kategóriás képzésekre vonatkoznak."],
  ["2. Jelentkezés és szerződéskötés", "Jelentkezni az ügyfélfogadó irodában, illetve előzetes online jelentkezéssel lehet. Az online űrlap elküldése még nem hoz létre képzési szerződést. A szerződés akkor jön létre, amikor az autósiskola a jelentkező feltételeit ellenőrizte, és a felek írásbeli, személyre szóló képzési szerződést kötnek. Kiskorú tanuló esetén a törvényes képviselő közreműködése és aláírása is szükséges."],
  ["3. A képzés feltételei", "A tanulónak meg kell felelnie a választott kategória jogszabályi életkori, egészségi, iskolai végzettségi és közlekedésbiztonsági feltételeinek. A felvételhez szükséges okmányokat és igazolásokat az autósiskola ellenőrizheti. Az elméleti képzés e-learning formában is történhet; az alaphozzáférés 75 óra, a képzés kezdetétől számított 180 nap. A részletes kategóriafeltételeket az írásbeli tájékoztató tartalmazza."],
  ["4. Díjak és fizetés", "A képzési és vizsgadíjakat az aktuális árlista, az írásbeli tájékoztató és a tanulóval kötött szerződés tartalmazza. A tanfolyam megkezdésének feltétele a szerződésben megjelölt első részlet és a szükséges vizsgadíjak megfizetése. A tandíj az irodában, számla ellenében vagy átutalással fizethető a 10410400-00000190-33608936 bankszámlára, kedvezményezett: Prémium Autósiskola. Az oktatónak készpénzt átadni nem szabad."],
  ["5. Oktatás, késés és lemondás", "A gyakorlati időpontokat a tanuló és az oktató előre egyezteti. Ha a tanóra a tanuló hibájából marad el, illetve a tanuló a rendtartás szerinti lemondási jogával nem él, a tervezett órák felének díját köteles megfizetni. Az oktató a tanuló megjelenésére az első 20 percben köteles várni. Ha a tanóra nem a tanuló hibájából marad el, az autósiskola másik időpontban biztosítja azt."],
  ["6. Vizsgák", "A vizsgára bocsátás feltétele a vonatkozó tantervi követelmények, az előírt óraszám és menettávolság, valamint a díjfizetési feltételek teljesítése. A tanulónak a vizsga helyszínén pontosan kell megjelennie és személyazonosságát igazolnia kell. A vizsgák részletes rendjét a vizsgaszervezet szabályai és az írásbeli tájékoztató ismerteti."],
  ["7. A képzés megszakítása és áthelyezés", "A tanuló írásbeli kérésére az autósiskola a képzést megszakítja, az addig elvégzett képzésről pedig hivatalos igazolást ad ki. A befizetett, de szolgáltatással nem teljesített díjrész visszajár; az autósiskola ezért kezelési költséget nem számít fel. Más képzőszervhez történő áthelyezésnél a tanuló a kedvezményeit elveszítheti, és a szerződésben rögzített különbözet fizetendő lehet."],
  ["8. Magatartási és biztonsági szabályok", "A tanuló köteles a baleset-, tűzvédelmi és oktatási szabályokat betartani. Alkohol vagy más bódító szer hatása alatt az oktatáson és vizsgán részt venni tilos. Súlyos rendzavarás vagy veszélyeztető magatartás esetén az autósiskola azonnali hatállyal megszüntetheti a szerződést; ilyen esetben a tandíj nem jár vissza."],
  ["9. Panaszkezelés", "Panaszt és észrevételt először az oktatónál, eredménytelenség esetén az ügyfélfogadó irodában vagy Kicska Gábor Zoltán iskolavezetőnél lehet jelezni. Az iskolavezető e-mail-címe: kicska82@gmail.com, telefonszáma: +36-30-235-2597. Fogadóórája szerdán 15:00–16:00 között, illetve előzetes telefonos egyeztetéssel van."],
  ["10. Adatkezelés és záró rendelkezések", "A személyes adatok kezeléséről az Adatkezelési tájékoztató rendelkezik. A jelen feltételekben nem szabályozott kérdésekben a Polgári Törvénykönyv, a járművezető-képzésre vonatkozó jogszabályok és a tanulóval kötött képzési szerződés az irányadó. A feltételek hatályos változata a weboldalon és az ügyfélfogadó irodában érhető el."],
];

const detailedConditions = [
  ["11. Kategóriánkénti felvételi feltételek", "AM képzésre a 14. életévet betöltött, vagy attól legfeljebb hat hónappal fiatalabb jelentkező vehető fel. A1-re 16, A2-re 18 éves, vagy az adott korhatárnál legfeljebb hat hónappal fiatalabb jelentkező jelentkezhet. A korlátlan A kategóriánál az életkor és az előzetes kategória feltételeit a tanuló egyéni helyzete alapján ellenőrizzük. B kategóriára a 17. életévet betöltött, illetve annál legfeljebb fél évvel fiatalabb jelentkező vehető fel. A1, A2, A és B kategóriánál első csoportú egészségügyi alkalmasság, valamint legalább alapfokú iskolai végzettség szükséges."],
  ["12. Elméleti és gyakorlati képzés", "Az elméleti tanfolyam teljesítése után lehet elméleti vizsgára jelentkezni. A gyakorlati oktatás a sikeres elméleti vizsga, a szükséges díjak befizetése és a kategória előírásai szerint indul. Az alapoktatás zárt tanpályán is történhet; a rutin- és vizsgapálya helyszíne Nyíregyháza, Törzs utca 108. A vezetési időpontok jellemzően előzetes egyeztetéssel, alkalmanként két tanórában kerülnek megszervezésre."],
  ["13. Tanulói jogok és kötelezettségek", "A tanuló jogosult a vállalási feltételek megismerésére, a képzésről és befizetéseiről részletes tájékoztatást kérni, panaszt tenni, továbbá írásban kérni a képzés megszakítását vagy áthelyezését. Köteles a díjakat a szerződésben meghatározott ütemezésben teljesíteni, a foglalkozásokon pontosan megjelenni, a közlekedési, baleset- és tűzvédelmi szabályokat betartani, valamint személyes adatainak változását nyolc napon belül bejelenteni."],
  ["14. Az autósiskola jogai és kötelezettségei", "Az autósiskola ellenőrzi a felvételi feltételeket és a szükséges okmányokat, a tanulóval egyedi képzési szerződést köt, a befizetésekről és szolgáltatásokról tájékoztatást ad, valamint a személyes és különleges adatokat bizalmasan kezeli. A tandíj elmaradása esetén a képzést szüneteltetheti. A képzés vagy a vizsgák rendjét súlyosan sértő magatartás esetén a szerződést azonnali hatállyal megszüntetheti."],
  ["15. Vizsgára bocsátás és vizsgarend", "A vizsgára bocsátáshoz a tanulónak az előírt tananyagot, óraszámot és menettávolságot teljesítenie kell, meg kell felelnie az életkori és alkalmassági feltételeknek, és a vizsgadíjat a vizsgára jelentés előtt meg kell fizetnie. A vizsgán a személyazonosságot igazolni kell. Sikertelen vizsga után új vizsga a hatályos vizsgaszabályok szerinti idő elteltével tehető. A részletes vizsgafeltételeket a KAV és az irányadó jogszabályok határozzák meg."],
  ["16. Díjak, pótórák és díjmódosítás", "A mindenkori képzési és vizsgadíjakat az aktuális webes árlista, az írásbeli tájékoztató és az egyedi képzési szerződés együtt tartalmazza. Pótóra a tanuló oktatónál jelzett igényére, az aktuális díjtábla szerinti áron vehető igénybe. Az elméleti, csoportos foglalkozás díjrészét a tanfolyam elindulása után nem lehet visszakérni. A gyakorlati óradíj módosításának lehetőségét az autósiskola fenntartja; erről az érintett tanulókat írásban tájékoztatja."],
  ["17. Elsősegély, okmánykiadás és külső díjak", "Az elsősegélynyújtási tanfolyam és vizsga feltételeit, valamint díjait az írásbeli tájékoztató tartalmazza. Sikeres forgalmi vizsga után a vezetői engedély kiadásához előírt igazolásokat és okmányokat a tanulónak kell bemutatnia a jogosult hatóságnál. Az orvosi alkalmasság, elsősegély és más, külső szolgáltatónál fizetendő díjak a képzési díjon felül merülhetnek fel."],
  ["18. Kapcsolattartás", "Az ügyfélfogadás helye: 4400 Nyíregyháza, Széchenyi utca 17. földszint 2U. ajtó. Ügyfélfogadás: kedd és csütörtök 12:00–16:00, más időpontban előzetes egyeztetéssel. E-mail: info@premiumautosiskola.hu. Az iskolavezető: Kicska Gábor Zoltán (azonosító: 12246), elérhetősége: kicska82@gmail.com, +36-30-235-2597; fogadóóra szerdán 15:00–16:00, illetve egyeztetett időpontban."],
  ["19. Képzési határidők és érvényesség", "A tanulónak az elméleti tanfolyam megkezdésétől számított, jogszabályban meghatározott időn belül sikeres elméleti vizsgát kell tennie. Az első sikeres elméleti vizsgától számítva a gyakorlati képzést és a forgalmi vizsgát is a vonatkozó jogszabályi határidőn belül kell teljesíteni. Ha valamely határidő lejár, a további teendőket — szükség esetén a tanfolyam vagy vizsga megismétlését — a hatályos szabályok és a KAV előírásai határozzák meg."],
  ["20. Órarend, késés és elmaradt foglalkozás", "A tanuló a gyakorlati óra kezdete előtt köteles megjelenni, az oktató a tanuló megérkezésére az első húsz percben vár. Lemondást vagy módosítást a tanuló az oktatóval előre, igazolható módon köteles egyeztetni. A tanuló érdekkörében elmaradt vagy kellő időben nem lemondott foglalkozásnál a tervezett órák felének díja fizetendő. Az oktató vagy az autósiskola oldalán felmerült elmaradás esetén pótidőpontot ajánlunk fel."],
  ["21. Gyakorlati oktatás rendje", "A tanuló a gyakorlati oktatás során köteles az oktató utasításait, a közúti közlekedés szabályait és az oktatójármű használatára vonatkozó előírásokat betartani. Motoros képzésen a kategóriához előírt, megfelelő védőfelszerelés viselése szükséges. A tanuló köteles jelezni, ha egészségi állapota, vezetésre való alkalmassága vagy okmányainak érvényessége megváltozik. Veszélyes vagy a képzést akadályozó állapotban az oktató a foglalkozást nem kezdi meg vagy megszakítja."],
  ["22. Áthelyezés, szünetelés és elszámolás", "A tanuló írásban kérheti a képzés szüneteltetését vagy más képzőszervhez történő áthelyezését. A Prémium Autósiskola az elvégzett képzésről az előírt igazolást kiadja. A fel nem használt, befizetett díjrész a képzési szerződés és a teljesítés alapján jár vissza; az írásbeli tájékoztató szerint az autósiskola megszakításkor külön adminisztrációs díjat nem számít fel. Másik képzőszervhez áthelyezéskor az ottani feltételek, díjak és esetleges különbözet a tanulót terhelhetik."],
  ["23. Panasz, tájékoztatás és adatvédelem", "A tanuló a képzés menetéről, a teljesített órákról, a befizetésekről és a vizsgára bocsátás feltételeiről tájékoztatást kérhet. Panaszát először az oktatónál, majd az ügyfélfogadásnál vagy az iskolavezetőnél érdemes jelezni, hogy azt mielőbb kivizsgálhassuk. A tanuló, törvényes képviselője vagy meghatalmazottja a személyes adatok kezelésére vonatkozó részletes szabályokat az Adatkezelési tájékoztatóban találja meg."],
  ["24. Záró rendelkezések", "A jelen feltételek és az írásbeli tájékoztató a mindenkori hatályos jogszabályokkal együtt alkalmazandó. Ha valamely rendelkezés érvénytelen vagy nem alkalmazható, az nem érinti a többi rendelkezés érvényességét. A felek vitás kérdéseiket elsőként egyeztetéssel rendezik. A feltételek mindenkori hatályos változata a weboldalon és az ügyfélfogadó irodában hozzáférhető."],
];

export default function TermsPage() { return <><Header /><main className="min-h-screen bg-[#15203a] pb-24 pt-32 text-slate-200"><article className="mx-auto max-w-4xl px-6"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-amber-400">Prémium Autósiskola</p><h1 className="mt-4 text-4xl font-black text-white md:text-5xl">Általános Szerződési Feltételek</h1><p className="mt-4 max-w-3xl leading-7 text-slate-300">A jelen feltételek az írásbeli tájékoztatóval és az egyedi képzési szerződéssel együtt értelmezendők. Eltérés esetén az egyedi szerződés és a kötelező jogszabályi előírás az irányadó.</p><p className="mt-4 text-sm text-slate-400">Hatályos: 2026. szeptember 25.</p><div className="mt-10 space-y-6">{[...sections, ...detailedConditions].map(([title, text]) => <section key={title} className="rounded-3xl border border-white/10 bg-white/5 p-6 leading-7 md:p-8"><h2 className="text-2xl font-black text-white">{title}</h2><p className="mt-4">{text}</p></section>)}</div><p className="mt-8 text-sm text-slate-400">Az online jelentkezés során kezelt adatok részleteit az <Link className="text-amber-300 underline underline-offset-4" href="/adatkezeles">Adatkezelési tájékoztató</Link> tartalmazza.</p></article></main><Footer settings={null} /></>; }
