import Link from "next/link";
import { CarFront, ShieldCheck, Sparkles } from "lucide-react";
import Footer from "@/app/components/Footer";
import Header from "@/app/components/Header";
import TrafficSituationDemo from "@/app/components/TrafficSituationDemo";
import { getPublicContent } from "@/lib/content";

export default async function TrafficSituationsPage() {
  const content = await getPublicContent();
  return <><Header /><main className="min-h-screen bg-[#15203a] pb-24 pt-32 text-white"><div className="mx-auto max-w-7xl px-6"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[0.24em] text-amber-300">Prémium gyakorlótér · bemutató</p><h1 className="mt-4 text-4xl font-black leading-tight sm:text-6xl">Forgalmi helyzetek,<br /><span className="text-amber-300">érthetően és interaktívan.</span></h1><p className="mt-6 text-lg leading-8 text-slate-300">Nem száraz szabályok, hanem olyan helyzetek, amelyekkel a valós forgalomban is találkozhatsz. Dönts, nézd meg az animációt, majd értsd meg az okát.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[{ icon: CarFront, title: "Valós helyzetek", text: "Kereszteződés, körforgalom, sávváltás és sok más szituáció." }, { icon: Sparkles, title: "Azonnali magyarázat", text: "Minden válasz után rövid, érthető indoklást kapsz." }, { icon: ShieldCheck, title: "Saját tempóban", text: "Biztonságos gyakorlás, még a forgalomba indulás előtt." }].map(({ icon: Icon, title, text }) => <div key={title} className="rounded-2xl border border-white/10 bg-white/[0.05] p-5"><Icon className="h-6 w-6 text-amber-300" /><p className="mt-4 font-black text-white">{title}</p><p className="mt-2 text-sm leading-6 text-slate-300">{text}</p></div>)}</div><div className="mt-10"><TrafficSituationDemo /></div><div className="mt-12 rounded-3xl border border-amber-300/25 bg-gradient-to-r from-amber-300/15 to-transparent p-7 md:flex md:items-center md:justify-between"><div><p className="text-xl font-black">Ez az első működő minta.</p><p className="mt-2 text-slate-300">A következő lépésben ebből építhetünk tematikus, több helyzetet tartalmazó gyakorlómodult.</p></div><Link href="/#kepzesek" className="mt-5 inline-flex rounded-xl bg-amber-400 px-5 py-3 font-black text-slate-950 transition hover:bg-amber-300 md:mt-0">Vissza a képzésekhez</Link></div></div></main><Footer settings={content.settings} /></>;
}
