import Link from "next/link";
import Footer from "@/app/components/Footer";
import Header from "@/app/components/Header";

const contact = {
  company: "Prémium Oktatás Korlátolt Felelősségű Társaság",
  shortName: "Prémium Oktatás Kft.",
  school: "Prémium Autósiskola",
  seat: "4400 Nyíregyháza, Toldi utca 69. 1. em. 11. ajtó",
  office: "4400 Nyíregyháza, Széchenyi utca 17. földszint 2U. ajtó",
  email: "info@premiumautosiskola.hu",
  phone: "+36-30-235-2597",
};

export const metadata = { title: "Adatkezelési tájékoztató" };

export default function PrivacyPage() {
  return <><Header /><main className="min-h-screen bg-[#15203a] pb-24 pt-32 text-slate-200"><article className="mx-auto max-w-4xl px-6"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-amber-400">Prémium Autósiskola</p><h1 className="mt-4 text-4xl font-black text-white md:text-5xl">Adatkezelési tájékoztató</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-300">Ez a tájékoztató leírja, hogyan kezeljük a weboldal látogatóinak és az online jelentkezőknek a személyes adatait.</p><p className="mt-4 text-sm text-slate-400">Hatályos: 2026. szeptember 25.</p><div className="mt-10 space-y-6">
  <Section title="1. Az adatkezelő és az elérhetőségei"><p><strong>{contact.company}</strong> ({contact.shortName}), kereskedelmi név: {contact.school}.</p><p className="mt-3">Székhely: {contact.seat}<br />Ügyfélfogadás: {contact.office}<br />Cégjegyzékszám: Cg. 15-09-086978<br />Adószám: 27289936-1-15<br />E-mail: <a className="text-amber-300 underline underline-offset-4" href={`mailto:${contact.email}`}>{contact.email}</a><br />Telefon: <a className="text-amber-300 underline underline-offset-4" href="tel:+36302352597">{contact.phone}</a></p><p className="mt-3">Adatvédelmi kérésedet az e-mail-címünkre vagy az ügyfélfogadó irodában nyújthatod be.</p></Section>
  <Section title="2. Milyen adatokkal és milyen célból dolgozunk?"><div className="space-y-5"><DataBlock title="A weboldal használata" text="A weboldal technikai működéséhez a böngésző által átadott, naplózási célú technikai adatok kezelése szükséges. Ezek célja az oldal biztonságos és hibamentes működtetése." basis="A GDPR 6. cikk (1) bekezdés f) pontja: jogos érdekünk a weboldal biztonságos üzemeltetése." /><DataBlock title="Online jelentkezés" text="A jelentkezéshez név-, születési, kapcsolattartási, lakcím-, azonosító okmány-, adóazonosító-, iskolai végzettségre, vezetői engedélyre és képzési választásra vonatkozó adatokat kérünk. Kiskorú jelentkezőnél a törvényes képviselő elérhetőségeit is kezeljük." basis="A GDPR 6. cikk (1) bekezdés b) pontja: szerződéskötést megelőző lépések, illetve a képzési szerződés teljesítése." /><DataBlock title="Orvosi alkalmassági igazolás" text="Az online jelentkezés során feltölthető orvosi alkalmassági igazolást csak akkor kezeljük, ha azt önként feltöltöd. A dokumentumhoz kizárólag a jelentkezés feldolgozására kijelölt munkatársak férnek hozzá." basis="A GDPR 9. cikk (2) bekezdés a) pontja: kifejezett hozzájárulás. A hozzájárulás bármikor visszavonható, de ez nem érinti a visszavonás előtti kezelés jogszerűségét." /><DataBlock title="Kapcsolat, panasz és képzés" text="A velünk e-mailben, telefonon vagy személyesen közölt adatokat a megkeresés megválaszolásához, a képzés adminisztrációjához, a vizsgáztatás szervezéséhez, a befizetések kezeléséhez és a jogszabályi kötelezettségeink teljesítéséhez használjuk." basis="Szerződés teljesítése, jogi kötelezettség teljesítése, illetve jogos érdek." /></div></Section>
  <Section title="3. Adatmegőrzés"><p>A jelentkezési adatokat a jelentkezés elbírálásáig, majd szerződéskötés esetén a képzési jogviszony teljesítéséig kezeljük. A számlázási, képzési, vizsga- és egyéb kötelező nyilvántartások adatait a rájuk vonatkozó jogszabályi megőrzési idő végéig őrizzük meg. A szerződéshez nem vezető jelentkezés adatait a szükséges egyeztetés lezárása után töröljük, kivéve, ha megőrzésüket jogvita vagy jogszabály indokolja.</p></Section>
  <Section title="4. Kik férhetnek hozzá az adatokhoz?"><p>Az adatokhoz a Prémium Oktatás Kft. feladatellátásra kijelölt munkatársai és oktatói férhetnek hozzá a szükséges mértékben. A weboldal és a jelentkezési rendszer üzemeltetésében tárhely- és informatikai szolgáltatók, köztük a Vercel Inc. és a Supabase Inc. közreműködhetnek adatfeldolgozóként. A jogszabályban előírt esetekben adatot adhatunk át az erre jogosult hatóságnak, vizsgaszervezetnek vagy könyvelési szolgáltatónak.</p><p className="mt-3">Az adatokat nem értékesítjük, és közvetlen üzletszerzési célú megkeresést nem küldünk hozzájárulás nélkül.</p></Section>
  <Section title="5. Sütik és helyi böngészőtárhely"><p>A jelenlegi weboldal nem használ marketing- vagy látogatottságmérő sütit. Az első látogatáskor megjelenő tájékoztató elfogadásának tényét kizárólag a saját böngésződ helyi tárhelyén rögzítjük, hogy a sávot ne kelljen minden oldalmegnyitáskor újra bezárnod. Ez a beállítás bármikor törölhető a böngésző adatai között.</p><p className="mt-3">Az adminisztrációs felület belépett felhasználói a munkamenet működéséhez szükséges technikai sütiket kaphatnak. Ezek nélkül az adminisztrációs felület nem használható.</p></Section>
  <Section title="6. Az érintett jogai és jogorvoslat"><p>Kérheted a rád vonatkozó személyes adatokhoz való hozzáférést, azok helyesbítését, törlését, kezelésének korlátozását, hordozhatóságát, és a jogos érdek alapján végzett kezelés ellen tiltakozhatsz. A hozzájárulásodat bármikor visszavonhatod. Kérésedre legkésőbb egy hónapon belül válaszolunk; szükség esetén a határidő további két hónappal meghosszabbítható.</p><p className="mt-3">Panasz esetén először kérjük, keresd meg az adatkezelőt a fenti elérhetőségeken. Emellett a <a className="text-amber-300 underline underline-offset-4" href="https://www.naih.hu/" target="_blank" rel="noreferrer">Nemzeti Adatvédelmi és Információszabadság Hatósághoz</a> is fordulhatsz, vagy bírósági jogorvoslatot kezdeményezhetsz.</p></Section>
  <Section title="7. Kapcsolódó feltételek"><p>A képzés feltételeit, díjait, az áthelyezés és a panaszkezelés rendjét az <Link className="text-amber-300 underline underline-offset-4" href="/altalanos-szerzodesi-feltetelek">Általános Szerződési Feltételek</Link> és az írásbeli tájékoztató részletezi.</p></Section>
  <Section title="8. A tájékoztató hatálya és alapelvei"><p>A tájékoztató a Prémium Autósiskola honlapját felkereső személyekre, az érdeklődőkre, az online vagy személyesen jelentkezőkre, a tanulókra, a törvényes képviselőkre és a velünk kapcsolatba lépő egyéb személyekre vonatkozik.</p><p className="mt-3">Csak olyan adatot kezelünk, amely a megjelölt célhoz szükséges. Az adatokat célhoz kötötten, a szükséges ideig, bizalmasan és megfelelő hozzáférési jogosultságok mellett kezeljük. Nem használjuk az adatokat olyan, e tájékoztatóval össze nem egyeztethető célra, amelyhez nincs jogalapunk.</p></Section>
  <Section title="9. Az online jelentkezés részletes adatai"><p>Az online jelentkezési űrlap a kapcsolatfelvételhez és a képzési szerződés előkészítéséhez kérhet nevet, születési adatokat, telefonszámot, e-mail-címet, lakcímet, a választott kategóriát, a vezetői engedélyre, iskolai végzettségre és egészségügyi alkalmasságra vonatkozó adatokat. A személyazonosító okmány és az adóazonosító jel adataira a szerződéskötés és a képzési adminisztráció során lehet szükség.</p><p className="mt-3">Kiskorú jelentkező esetén a törvényes képviselő neve és elérhetősége is szükséges lehet. A vezetési tapasztalatra, az előzetes kategóriákra, az áthelyezésre, illetve a kívánt vezetési időpontokra vonatkozó információk a képzés szervezését segítik.</p><p className="mt-3">A kötelezőként jelölt adatok hiányában a jelentkezés érdemi feldolgozása vagy a képzési szerződés megkötése nem lehetséges. Az egészségügyi igazolás feltöltése az online űrlapon önkéntes; ezt az adatot nem kérjük marketingcélból és nem használjuk fel arra.</p></Section>
  <Section title="10. Kapcsolatfelvétel, ügyintézés és panasz"><p>Az e-mailben, telefonon, személyesen vagy az online űrlapon küldött megkeresésből kezelhetjük a nevet, elérhetőséget, az ügy tartalmát, a kapcsolódó iratokat, valamint az ügyintézéshez szükséges további adatokat. Ezeket az információkat a kérdés megválaszolásához, a jelentkezés nyomon követéséhez, a panasz kivizsgálásához és az esetleges jogi igények kezeléséhez használjuk.</p><p className="mt-3">Panasz esetén az ügyben érintett oktató, az ügyfélfogadásra kijelölt munkatárs és az iskolavezető a feladatához szükséges körben ismerheti meg az adatokat. A panaszra adott válasz és a kapcsolódó dokumentumok megőrzésére a panaszkezelési, számviteli vagy egyéb jogi kötelezettség időtartama irányadó.</p></Section>
  <Section title="11. Képzési, pénzügyi és vizsgáztatási adminisztráció"><p>A képzési szerződés teljesítéséhez kezeljük a tanfolyamra, foglalkozásokra, haladásra, hiányzásra, vizsgára jelentésre, befizetésekre, számlákra, kedvezményekre, áthelyezésre és a tanuló által benyújtott igazolásokra vonatkozó adatokat. Az adatkezelés jogalapja elsősorban a szerződés teljesítése, illetve az autósiskolát terhelő jogszabályi és hatósági kötelezettség.</p><p className="mt-3">A vizsgára jelentéshez, a hatósági nyilvántartásba történő továbbításhoz vagy az ellenőrzéshez kizárólag a szükséges adatokat adjuk át az illetékes vizsgaszervezetnek, hatóságnak vagy egyéb jogszabály alapján jogosult szervezetnek.</p></Section>
  <Section title="12. Adatmegőrzési szempontok"><p>A különböző iratok megőrzési ideje eltérő lehet. A szerződéshez, képzéshez és vizsgához kapcsolódó adatokat a jogviszony teljesítéséhez, valamint az előírt nyilvántartási és ellenőrzési kötelezettségek teljesítéséhez szükséges ideig őrizzük. A számlák és pénzügyi bizonylatok megőrzésére a számviteli szabályok szerinti idő vonatkozik.</p><p className="mt-3">Ha a jelentkezésből nem lesz szerződés, a jelentkezési adatokat az egyeztetés lezárása után töröljük, kivéve ha jogszabály, folyamatban lévő panasz vagy jogvita indokolja a további megőrzést. Az önkéntesen feltöltött orvosi igazolást a jelentkezés elbírálásához és a képzési ügyintézéshez szükséges ideig kezeljük, majd a megőrzés alapjának megszűnésekor töröljük vagy a jogszabályi megőrzéshez igazítjuk.</p></Section>
  <Section title="13. Címzettek, adatfeldolgozók és adattovábbítás"><p>A társaság kijelölt munkatársain kívül adatfeldolgozóként működhetnek közre a weboldal, tárhely, adatbázis, levelezés, könyvelés és informatikai rendszerek szolgáltatói. A weboldal működésében jelenleg a Vercel Inc. és a Supabase Inc. technikai szolgáltatása vehet részt. Ezek a szolgáltatók csak a szolgáltatásuk teljesítéséhez szükséges mértékben kezelhetnek adatot.</p><p className="mt-3">Adatot akkor továbbítunk vizsgaszervezetnek, közlekedési hatóságnak, könyvelőnek, biztosítónak vagy más címzettnek, ha azt a képzés szervezése, jogszabály, hatósági megkeresés vagy a szerződés teljesítése megköveteli. Személyes adatot nem adunk el, nem végzünk profilalkotást, és nem küldünk reklámüzenetet külön hozzájárulás nélkül.</p></Section>
  <Section title="14. Adatbiztonság"><p>Az adatokat olyan szervezési és technikai intézkedésekkel védjük, amelyek az illetéktelen hozzáférés, megváltoztatás, nyilvánosságra hozatal, elvesztés vagy megsemmisülés kockázatát csökkentik. A hozzáférést a feladat ellátásához szükséges személyekre korlátozzuk; az elektronikus rendszereinknél jogosultságkezelést és jelszavas hozzáférést alkalmazunk.</p><p className="mt-3">Ha olyan adatvédelmi incidens történne, amely várhatóan kockázatot jelent az érintettek jogaira és szabadságaira, a vonatkozó szabályok szerint megtesszük a szükséges bejelentést és tájékoztatást.</p></Section>
  <Section title="15. Kérelmek intézése és az érintetti jogok gyakorlása"><p>Kérésedet küldheted e-mailben az <a className="text-amber-300 underline underline-offset-4" href={`mailto:${contact.email}`}>{contact.email}</a> címre, vagy leadhatod az ügyfélfogadó irodában. A kérelemben írd le, milyen adatra vagy intézkedésre vonatkozik a kérés. Szükség esetén azonosítást kérhetünk, hogy az adatot csak az arra jogosult személynek adjuk ki.</p><p className="mt-3">A hozzáféréshez, helyesbítéshez, törléshez, korlátozáshoz, adathordozhatósághoz és tiltakozáshoz való jog a GDPR-ban meghatározott feltételekkel gyakorolható. Kérésed teljesítéséről főszabály szerint egy hónapon belül tájékoztatunk. A kérelem teljesítése díjmentes; ismétlődő vagy nyilvánvalóan megalapozatlan kérelem esetén a jogszabály által megengedett módon járunk el.</p></Section>
  <Section title="16. Hozzájárulás visszavonása és jogorvoslat"><p>Az olyan adatkezelésnél, amelyhez hozzájárulást adtál — például az online feltöltött orvosi alkalmassági igazolásnál — hozzájárulásodat bármikor visszavonhatod. A visszavonás nem teszi jogellenessé a korábban, a hozzájárulás alapján végzett adatkezelést, és nem érinti azokat az adatkezeléseket, amelyek szerződés vagy jogszabály alapján továbbra is szükségesek.</p><p className="mt-3">Ha úgy gondolod, hogy adataid kezelésével kapcsolatban jogsérelem ért, először keresd a társaságot. Panaszt tehetsz a <a className="text-amber-300 underline underline-offset-4" href="https://www.naih.hu/" target="_blank" rel="noreferrer">Nemzeti Adatvédelmi és Információszabadság Hatóságnál</a>, és bírósághoz is fordulhatsz.</p></Section>
  </div></article></main><Footer settings={null} /></>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-3xl border border-white/10 bg-white/5 p-6 leading-7 md:p-8"><h2 className="text-2xl font-black text-white">{title}</h2><div className="mt-4 text-slate-200">{children}</div></section>; }
function DataBlock({ title, text, basis }: { title: string; text: string; basis: string }) { return <div><h3 className="font-black text-white">{title}</h3><p className="mt-1">{text}</p><p className="mt-2 text-sm text-slate-400"><strong className="text-slate-300">Jogalap:</strong> {basis}</p></div>; }
